version: "3.3"
services:
  server:
    container_name: node
    image: node_server_image
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
  
  db:
    container_name: mongo
    image: mongo
    ports:
      - "3000:27017"
    volumes:
      - ./dbData:/data/db
  
  web:
    container_name: angular
    image: angular_app_image
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - server
